sudo: false
dist: trusty

language: php

matrix:
  include:
    - env: TRAVISCI=phpunit
    - env: TRAVISCI=phpcs

before_script:
  - |
    if [[ "$TRAVISCI" == "phpunit" ]] ; then
      composer require phpunit/phpunit 7.*
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      composer require squizlabs/php_codesniffer
      composer require phpcompatibility/php-compatibility
      vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
    fi

script:
  - |
    if [[ "$TRAVISCI" == "phpunit" ]] ; then
      vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-text
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs --standard=tests/.phpcs.xml
    fi
